### ISSUE TITLE
Is the library need ms word installed on the serverside?

### ISSUE THREAD

**Issue by softboy99** [airxiechao/oarword2#6]
Is the library need ms word installed on the serverside? or pure client silde  and only need the http url of the word doc?

**Comment by airxiechao** [comment]
no need ms word

**Comment by softboy99** [comment]
Is it need server side? or and only need the http url of the word doc?

**Comment by airxiechao** [comment]
This is a ms-word like editor running in browser, document edition operations do not need backend server. But if you want other functions such as import/export, then require server-side program.
